### ISSUE TITLE
Too many errors while preprocess_pdbbind.

### ISSUE THREAD

**Issue by moonblue333** [agave233/SIGN#1]
1.  which version of chimera? is there a way to batch-convert?
2.  which version of openbabel?
3.  where to download core-set?  CASF-2016?
4.  can the github code preprocess fold 2016 successfully?  

errors, such as:

==============================
*** Open Babel Warning  in ReadMolecule
  Failed to kekulize aromatic bonds in MOL2 file (title is 1o5c_ligand)

==============================
*** Open Babel Warning  in ReadMolecule
  Failed to kekulize aromatic bonds in MOL2 file (title is 3m89_ligand)

==============================
*** Open Babel Warning  in PerceiveBondOrders
  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders (title is data_2016/refined-set/4u4x/4u4x_protein.pdb)

Traceback (most recent call last):
  File "preprocess_pdbbind.py", line 360, in <module>
  File "preprocess_pdbbind.py", line 317, in process_dataset
    refined_data.append(graph)
ValueError: too many values to unpack (expected 3)

**Comment by agave233** [comment]
1. Our used version is chimera 1.13.1rc. 
Maybe you have two ways to convert all PDB files in a folder :
  1.1) For Linux OS, you can refer to this code: https://gitlab.com/cheminfIBB/pafnucy/-/blob/master/pdbbind_data.ipynb. 
  1.2) For Windows OS (we used), you can use the following demo script run.py:
```python
'''
run.py
'''
import os
from tqdm import tqdm

def main(file_path):
    pdb_list = [k for k in os.listdir(file_path) if len(k) == 4 and not os.path.isfile(file_path + "%s/%s_pocket.mol2" % (k, k))]
    print(len(pdb_list))
    count = 0
    for name in tqdm(pdb_list):
        if len(name) != 4:
            continue
        PDB_file = file_path + name + '/' + name
        os.system(" chimera --nogui process.py %s" % PDB_file)
        count += 1
    print(count)

file_path = "YOUR PATH"
main(file_path)
```

```python
'''
process.py
'''
import chimera
from DockPrep import prep, AddH
from WriteMol2 import writeMol2
import sys
import os

PDB_file = sys.argv[-1]
file_path = "YOUR PATH"
PDB_file = file_path + PDB_file + '/' + PDB_file
protein=chimera.openModels.open('%s_pocket.pdb'%PDB_file)
prep(protein,addHFunc=AddH.hbondAddHydrogens ,addCharges=True)
writeMol2(protein, "%s_pocket.mol2" % PDB_file)
```

2. The version of openbabel is 3.1.1
3. You can download the dataset from the website: http://www.pdbbind.org.cn/download.php
4. We have fixed the codes now. 
  Please note that the error message like "*** Open Babel Warning in ReadMolecule Failed to kekulize aromatic bonds in MOL2 file (title is 1o5c_ligand)" is actually the warning, which won't have a great impact.
