### ISSUE TITLE
Unable to run on Windows

### ISSUE THREAD

**Issue by erikedlund** [agave233/SIGN#2]
Attempting to train the model on Windows I hit the following exception: 

```
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'
```

**Comment by agave233** [comment]
It seems that his error comes from the multiprocessing package.
Maybe you can check your environment 'pgl'?

**Comment by erikedlund** [comment]
I found some discussion suggesting that 'fork' is not available on Windows, so multiprocessing must be configured to use 'spawn' instead. Some people report success using 'fork on WSL, also. https://issueexplorer.com/issue/uber/orbit/486
